<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Lqn5ZOB5qGI5L6L');
$cfg_Cs[2]=array(0,1,0,'5paH56ug5Yqo5oCB');
$cfg_Cs[3]=array(0,1,1,'5ZON5bqU5rWL6K+V');
$cfg_Cs[4]=array(0,1,1,'5Yqg5YWl5oiR5Lus');
$cfg_Cs[5]=array(1,1,1,'6aOf5ZOB');
$cfg_Cs[6]=array(1,1,1,'55Sf5rS7');
$cfg_Cs[11]=array(1,1,1,'5pys5YWs5Y+45pu05aSa5Lqn5ZOBLOivt+iBlOezu+WuouacjeOAguS7juS4muWNgeS9meW5tCznlJ/kuqfojIPlm7TmtrXnm5blpJrpoobln5/vvIw=');
$cfg_Cs[15]=array(2,1,0,'5YWs5Y+45paw6Ze7');
?>