<?php
$z[0]=Array("global","",96,125);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",232,261);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",503,725);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li class='active'><a href='~typelink~' style='color:white;'>~typename~</a></li>";

?>