<?php
$z[0]=Array("field","",84,103);
$z[0][4]['name']="title";
$z[1]=Array("global","",104,130);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",175,197);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",241,292);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",528,557);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",622,651);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",736,765);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",838,867);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("global","",919,948);
$z[8][4]['name']="cfg_templeturl";
$z[9]=Array("global","",1003,1032);
$z[9][4]['name']="cfg_templeturl";
$z[10]=Array("include","",1085,1120);
$z[10][4]['filename']="head.htm";
$z[11]=Array("channel","\r\n        	 <a href=\"[field:typeurl/]\" class=\"btn btn-default\">[field:typename/]</a>\r\n             ",1473,1699);
$z[11][4]['type']="son";
$z[11][4]['currentstyle']="<a href='~typelink~' class='btn btn-default btn-primary'>~typename~</a>";
$z[12]=Array("list","\r\n        	<li>\r\n              <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n              <img src=\"[field:litpic/]\" alt=\"[field:title/]\" />\r\n              <p>网站设计<br /><strong>[field:title/]</strong><br />[field:id function=GetTags(@me)/]</p></a>\r\n            </li>\r\n           ",1832,2155);
$z[12][4]['pagesize']="12";
$z[13]=Array("pagelist","",2273,2329);
$z[13][4]['listitem']="pre,next,pageno";
$z[13][4]['listsize']="5";
$z[14]=Array("include","",2390,2425);
$z[14][4]['filename']="dock.htm";

?>